steps:
  - label: "hammer: Build"
    command: "scripts/build.sh"
    key: build

  - label: ":test-tube: Test"
    command: "scripts/test.sh"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: "scripts/deploy.sh"
    key: deploy
    depends_on: test
